server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flask?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: consumer0 #服务名称--调用的时候根据名称来调用该服务的方法
provider:
  name: fang1
mybatis:
  mapper-locations: classpath:mybatis/*.xml

eureka:
  client:
    serviceUrl: #注册中心的注册地址
      defaultZone: http://127.0.0.1:8081/eureka/
    register-with-eureka: false