server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flask?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:com/example/demo/Dao/*.xml
  type-aliases-package: com.example.demo.domain